config/routes.rb
Rails.application.routes.draw do
  resources :logins
  resources :users

  get '/home', to: 'pages#home'
  get '/command_injection', to: 'pages#command_injection'
  get '/search1', to: 'pages#search1' # Injection - Command Injection

  get '/sql_injection', to: 'pages#sql_injection'
  get '/search2', to: 'pages#search2' # Injection - SQL Injection

  # Broken Authentication - Password Complexity => users#create

  # Broken Authentication - Information Leakage => logins#create

  # Sensitive Data Exposure => get /users/

  get '/xxe', to: 'pages#xxe'
  post '/content1', to: 'pages#content1' # XML External Entities (XXE)

  # Broken Access Control => post /users?user[admin]=1

  # Security Misconfiguration is in config/initializers/filter_parameter_logging.rb

  get '/xss', to: 'pages#xss'
  post '/content2', to: 'pages#content2' # Cross Site Scripting


  get '/insecure_deserialization', to: 'pages#insecure_deserialization'
  post '/content3', to: 'pages#content3' # Insecure Deserialization

  # Using Components with Known Vulnerabilities #=> Gemfile

  # Insufficient Logging Monitoring # post logins#create => Add log message
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/login.rb
class Login < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  def self.read_content
    if YAML.load_file('lib/content.yml')['content'].include?('SECRET')
      return "no thanks!"
    end
  end
end

app/models/user_content.rb
class UserContent
  def self.read_content
    return YAML.load(File.read(File.expand_path('lib/content.yml' )))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :set_login, only: [:show, :edit, :update, :destroy]

  # GET /logins
  # GET /logins.json
  def index
    @logins = Login.all
  end

  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  def create
    @user = User.find_by(username: login_params[:username])

    @success = (@user && @user.password == login_params[:password])

    if (!@success)
      failure_message = "Your login was unsuccessful."
    end

    respond_to do |format|
      if @success
        logger.error("[DOMAIN=AUTHENTICATION] [RESULT=SUCCESS] Successful login detected")

        format.html { redirect_to logins_path, notice: 'Login was successful.' }

      else
        logger.error("[DOMAIN=AUTHENTICATION] [RESULT=FAILURE] Login failure detected")
        format.html { redirect_to new_login_path, alert: failure_message }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  def destroy
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:username, :password)
    end
end

app/controllers/pages_controller.rb
require 'user_content'

class PagesController < ApplicationController
  def home
  end

  def command_injection
  end

  def sql_injection
  end

  def search1
    render 'command_injection'
  end

  def search2
    @users = User.where(username: params[:search])
    render 'sql_injection'
  end

  def xxe
  end

  def content1
    xml_doc  = Nokogiri::XML(params[:content])

    @content = xml_doc

    render 'xxe'
  end

  def xss
  end

  def content2
    @content = params[:content]

    render 'xss'
  end

  def insecure_deserialization
    @content = User.read_content
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
      @user = User.new(user_params)

      respond_to do |format|
        if @user.save
          format.html { redirect_to @user, notice: 'User was successfully created.' }
          format.json { render :show, status: :created, location: @user }
        else
          format.html { render :new }
          format.json { render json: @user.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation, :admin)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CybersecurityRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div><%= link_to 'Sign Up', new_user_path %> <%= link_to 'Log In', new_login_path %></div>
    <%= yield %>
  </body>
</html>

app/views/logins/_form.html.erb
<%= form_with(model: login, local: true) do |form| %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing Login</h1>

<%= render 'form', login: @login %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Logins</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.username %></td>
        <td><%= login.password %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login', new_login_path %>

app/views/logins/new.html.erb
 <% if flash[:alert].present? %>
 <span style="color: red;"><%= flash[:alert] %></span>
 <% end %>

<h1>New Login</h1>

<%= render 'form', login: @login %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @login.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @login.password %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>

app/views/pages/command_injection.html.erb
<%= form_tag("/search1", method: "get") do %>
    <%= label_tag(:search, "Search:") %>
    <%= text_field_tag(:search) %>
    <%= submit_tag("Submit") %>
<% end %>

<% if(params[:search]) %>

  <% if params[:search].include?(';') %>
    ";" not allowed
  <% else %>
    <%= `find . -iname #{params[:search]};` %>
  <% end %>
<% end %>

app/views/pages/home.html.erb
<%= form_tag("/search", method: "get") do %>
    <%= label_tag(:search, "Search:") %>
    <%= text_field_tag(:search) %>
    <%= submit_tag("Submit") %>
<% end %>

<% if(params[:search]) %>

  <%= `find . -iname #{params[:search]};` %>
<% end %>

app/views/pages/insecure_deserialization.html.erb
<br />
<br />

<% if @content %>
  <%= @content %>
<% end %>

app/views/pages/sql_injection.html.erb
<%= form_tag("/search2", method: "get") do %>
    <%= label_tag(:search, "Search:") %>
    <%= text_field_tag(:search) %>
    <%= submit_tag("Submit") %>
<% end %>

<% if(@users.present?) %>

<br />
We found the following users:
<br />
<br />
  <% @users.each do |user| %>
    <%= user.username %><br />
  <% end %>
<% end %>

app/views/pages/xss.html.erb
<!-- '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' --disable-xss-auditor -->
<!-- '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' --enable-xss-auditor -->

<%= form_tag("/content2", method: "post") do %>
    <br />
    <br />

    <%= label_tag(:content, "Content:") %>
    <%= text_field_tag(:content) %>

    <br />
    <br />

    <%= submit_tag("Submit") %>
<% end %>

<br />
<br />

<% if @content %>
  <%= raw @content %>
<% end %>

app/views/pages/xxe.html.erb
<!--

<?xml version="1.0" encoding="ISO-8859-1"?>
 <!DOCTYPE foo [
   <!ELEMENT foo ANY >
   <!ENTITY xxe SYSTEM "file:///etc/passwd" >]><foo>&xxe;</foo>

 -->

<%= form_tag("/content1", method: "post") do %>
    <br />
    <br />

    <%= label_tag(:content, "XML:") %>
    <%= text_area_tag(:content) %>
    <br />
    <br />
    <%= submit_tag("Submit") %>
<% end %>

<br />
<br />

<% if @content %>
  <%= @content %>
<% end %>

app/views/users/_form.html.erb
<p id="notice"><%= notice %></p>

<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Admin</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.admin %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
<p>
  <strong>Admin:</strong>
  <%= @user.admin %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>